export const Catalog = {
  courses : [{
    courseTitle: "Intro to Programming",
    instructor:  "Lloyd Reid",
    description: "Learn the basics of programming with instructor Lloyd Reid.",
    location: "online",
    startTime: "18:00",
    endTime: "21:00",
    meetingDay: ["MO", "WE"],
    startDate: "January 3, 2022 18:00",
    startEndTime: "January 3, 2022 21:00",
    endDate: "February 16, 2022",
    recurrence: "WEEKLY",
    prerequisites : false
  },
  {
    courseTitle: "Full-Time Full-Stack",
    instructor: "Vladimir Benton",
    description: "Ready to change your career? Learn all about back-end to front-end programming in a 40 hour-a-week program with esteemed instructor Vladimir Bent",
    location: "1945 SE Water Ave, Portland, OR 97214",
    startTime: "09:00",
    endTime: "17:00",
    meetingDays: ["MO", "TU", "WE", "TH", "FR"],
    startDate: "January 3, 2022 09:00",
    startEndTime: "January 3, 2022 17:00",
    endDate: "July 11, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "Part-Time Full-Stack",
    instructor: "Margrét Mitre Gardner",
    description: "Learn how to become a full-stack programmer in a part-time curriculum that takes place on the evenings. Taught by Margrét Mitre Gardner.",
    location: "online",
    startTime: "17:00",
    endTime: "21:00",
    meetingDays: ["SU", "MO", "TU", "WE"],
    startDate: "January 3, 2022 17:00",
    startEndTime: "January 3, 2022 21:00",
    endDate: "October 2, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "JavaScript I",
    instructor: "Linford Adamo",
    description: "Learn the fundamentals of JavaScript with instructor Linford Adamo.",
    location: "1945 SE Water Ave, Portland, OR 97214",
    startTime: "10:00",
    endTime: "12:00",
    meetingDays: ["MO", "WE", "FR"],
    startDate: "January 3, 2022 10:00",
    startEndTime: "January 3, 2022 12:00",
    endDate: "March 4, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "JavaScript II",
    instructor: "Linford Adamo",
    description: "Learn intermediate JavaScript with Linford Adamo. Students must take the JavaScript I course prior to registering for this course.",
    location: "1945 SE Water Ave, Portland, OR 97214",
    startTime: "10:00",
    endTime: "12:00",
    meetingDays: ["MO", "WE", "FR"],
    startDate: "March 14, 2022 10:00",
    startEndTime: "March 14, 2022 12:00",
    endDate: "May 27, 2022",
    recurrence: "WEEKLY",
    prerequisites: true
  },
  {
    courseTitle: "React",
    instructor: "Abraham Hancock",
    description: "Learn how to program in React with Abraham Hancock.",
    location: "211 SE Caruthers St, Portland, OR 97214",
    startTime: "13:00",
    endTime: "16:00",
    meetingDays: ["TU", "TH"],
    startDate: "June 7, 2022 13:00",
    startEndTime: "June 7, 2022 16:00",
    endDate: "August 18, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "C++",
    instructor: "Carmel Raymund",
    description: "Learn how to program in C++ with expert Carmel Raymund.",
    location: "211 SE Caruthers St, Portland, OR 97214",
    startTime: "09:00",
    endTime: "12:00",
    meetingDays: ["WE", "FR"],
    startDate: "January 3, 2022 09:00",
    startEndTime: "January 3, 2022 12:00",
    endDate: "March 18, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "C#",
    instructor: "Stevo Theofilus Abbatantuono",
    description: "Learn how to program in C# with Stevo Abbatantuono.",
    location: "1945 SE Water Ave, Portland, OR 97214",
    startTime: "13:00",
    endTime: "15:00",
    meetingDays: ["MO", "WE", "FR"],
    startDate: "January 3, 2022 13:00",
    startEndTime: "January 3, 2022 15:00",
    endDate: "March 18, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "Ruby",
    instructor: "Margrét Mitre Gardner",
    description: "Learn how to program in Ruby with instructor Margrét Mitre Gardner",
    location: "online",
    startTime: "09:00",
    endTime: "12:00",
    meetingDays: ["MO", "FR"],
    startDate: "January 3, 2022 09:00",
    startEndTime: "January 3, 2022 12:00",
    endDate: "April 22, 2022",
    recurrence: "WEEKLY",
    prerequisites: true
  },
  {
    courseTitle: "Python",
    instructor: "Lloyd Reid",
    description: "Learn how to work in Python in this course taught by Lloyd Reid.",
    location: "online",
    startTime: "09:00",
    endTime: "11:00",
    meetingDays: ["TU", "FR"],
    startDate: "January 3, 2022 09:00",
    startEndTime: "January 3, 2022 11:00",
    endDate: "April 1, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "Algorithms and Data Structures",
    instructor: "Ingebjørg Gulbadan",
    description: "Do you want to know more about computer science and the math that goes behind computer programming? Take this 6-week elective with Dr. Gulbadan, PhD.",
    location: "211 SE Caruthers St, Portland, OR 97214",
    startTime: "15:00",
    endTime: "17:00",
    meetingDays: ["FR"],
    startDate: "January 7, 2022 15:00",
    startEndTime: "January 7, 2022 17:00",
    endDate: "February 18, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  },
  {
    courseTitle: "Java",
    instructor: "Abraham Hancock",
    description: "Learn how to program in Java with Abraham Hancock.",
    location: "1945 SE Water Ave, Portland, OR 97214",
    startTime: "13:00",
    endTime: "16:00",
    meetingDays: ["MO", "WE"],
    startDate: "January 3, 2022 13:00",
    startEndTime: "January 3, 2022 16:00",
    endDate: "April 22, 2022",
    recurrence: "WEEKLY",
    prerequisites: false
  }] 
};